name = "GaussianProcessRegression"
uuid = "40f2fb2d-177c-4d19-8dec-6ef5c5103da2"
authors = ["srinix <srinix@protonmail.com> and contributors"]
version = "0.1.0"

[deps]
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParallelArrays = "862b1c87-f07d-406f-9f31-85f9a7d9607f"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]